#############################################################################
# Makefile for building: qtunneler
# Generated by qmake (2.01a) (Qt 4.5.2) on: st 4 7 15:42:51 2010
# Project:  qtunneler.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile qtunneler.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Base.cpp \
		BaseWall.cpp \
		BitmapObj.cpp \
		Border.cpp \
		Clicker.cpp \
		Communicator.cpp \
		Controller.cpp \
		Dispatcher.cpp \
		Evaluator.cpp \
		Explosion.cpp \
		GameWindow.cpp \
		InitDialog.cpp \
		Initializer.cpp \
		main.cpp \
		Matrix.cpp \
		Model.cpp \
		NetReceiver.cpp \
		NetSender.cpp \
		OrientedRoundObj.cpp \
		Packet.cpp \
		PacketQueue.cpp \
		Projectile.cpp \
		QueueReceiver.cpp \
		QueueSender.cpp \
		RoundObj.cpp \
		SettingsController.cpp \
		SettingsDialog.cpp \
		SettingsModel.cpp \
		Stone.cpp \
		Tank.cpp \
		View.cpp moc_Communicator.cpp \
		moc_GameWindow.cpp \
		moc_InitDialog.cpp \
		moc_Initializer.cpp \
		moc_Model.cpp \
		moc_SettingsController.cpp \
		moc_SettingsDialog.cpp \
		moc_SettingsModel.cpp \
		moc_View.cpp \
		qrc_tile.cpp
OBJECTS       = Base.o \
		BaseWall.o \
		BitmapObj.o \
		Border.o \
		Clicker.o \
		Communicator.o \
		Controller.o \
		Dispatcher.o \
		Evaluator.o \
		Explosion.o \
		GameWindow.o \
		InitDialog.o \
		Initializer.o \
		main.o \
		Matrix.o \
		Model.o \
		NetReceiver.o \
		NetSender.o \
		OrientedRoundObj.o \
		Packet.o \
		PacketQueue.o \
		Projectile.o \
		QueueReceiver.o \
		QueueSender.o \
		RoundObj.o \
		SettingsController.o \
		SettingsDialog.o \
		SettingsModel.o \
		Stone.o \
		Tank.o \
		View.o \
		moc_Communicator.o \
		moc_GameWindow.o \
		moc_InitDialog.o \
		moc_Initializer.o \
		moc_Model.o \
		moc_SettingsController.o \
		moc_SettingsDialog.o \
		moc_SettingsModel.o \
		moc_View.o \
		qrc_tile.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtunneler.pro
QMAKE_TARGET  = qtunneler
DESTDIR       = 
TARGET        = qtunneler

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtunneler.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qtunneler.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qtunneler.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtunneler1.0.0 || $(MKDIR) .tmp/qtunneler1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtunneler1.0.0/ && $(COPY_FILE) --parents Base.h BaseWall.h BitmapObj.h Border.h Clicker.h Communicator.h Controller.h DefaultValues.h Dispatcher.h Evaluator.h Explosion.h GameWindow.h InitDialog.h Initializer.h InitVector.h Matrix.h Model.h NetReceiver.h NetSender.h OrientedRoundObj.h Packet.h PacketQueue.h Player.h Projectile.h QueueReceiver.h QueueSender.h Receiver.h RoundObj.h Sender.h SettingsController.h SettingsDialog.h SettingsModel.h Stone.h Tank.h View.h .tmp/qtunneler1.0.0/ && $(COPY_FILE) --parents tile.qrc .tmp/qtunneler1.0.0/ && $(COPY_FILE) --parents Base.cpp BaseWall.cpp BitmapObj.cpp Border.cpp Clicker.cpp Communicator.cpp Controller.cpp Dispatcher.cpp Evaluator.cpp Explosion.cpp GameWindow.cpp InitDialog.cpp Initializer.cpp main.cpp Matrix.cpp Model.cpp NetReceiver.cpp NetSender.cpp OrientedRoundObj.cpp Packet.cpp PacketQueue.cpp Projectile.cpp QueueReceiver.cpp QueueSender.cpp RoundObj.cpp SettingsController.cpp SettingsDialog.cpp SettingsModel.cpp Stone.cpp Tank.cpp View.cpp .tmp/qtunneler1.0.0/ && (cd `dirname .tmp/qtunneler1.0.0` && $(TAR) qtunneler1.0.0.tar qtunneler1.0.0 && $(COMPRESS) qtunneler1.0.0.tar) && $(MOVE) `dirname .tmp/qtunneler1.0.0`/qtunneler1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtunneler1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Communicator.cpp moc_GameWindow.cpp moc_InitDialog.cpp moc_Initializer.cpp moc_Model.cpp moc_SettingsController.cpp moc_SettingsDialog.cpp moc_SettingsModel.cpp moc_View.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Communicator.cpp moc_GameWindow.cpp moc_InitDialog.cpp moc_Initializer.cpp moc_Model.cpp moc_SettingsController.cpp moc_SettingsDialog.cpp moc_SettingsModel.cpp moc_View.cpp
moc_Communicator.cpp: Communicator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Communicator.h -o moc_Communicator.cpp

moc_GameWindow.cpp: View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		GameWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GameWindow.h -o moc_GameWindow.cpp

moc_InitDialog.cpp: GameWindow.h \
		View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		InitVector.h \
		InitDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InitDialog.h -o moc_InitDialog.cpp

moc_Initializer.cpp: GameWindow.h \
		View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		InitDialog.h \
		InitVector.h \
		SettingsModel.h \
		Player.h \
		SettingsController.h \
		SettingsDialog.h \
		Communicator.h \
		Initializer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Initializer.h -o moc_Initializer.cpp

moc_Model.cpp: DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		Model.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Model.h -o moc_Model.cpp

moc_SettingsController.cpp: SettingsDialog.h \
		SettingsModel.h \
		Player.h \
		Communicator.h \
		SettingsController.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SettingsController.h -o moc_SettingsController.cpp

moc_SettingsDialog.cpp: SettingsModel.h \
		Player.h \
		SettingsDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SettingsDialog.h -o moc_SettingsDialog.cpp

moc_SettingsModel.cpp: Player.h \
		SettingsModel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) SettingsModel.h -o moc_SettingsModel.cpp

moc_View.cpp: Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		View.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View.h -o moc_View.cpp

compiler_rcc_make_all: qrc_tile.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_tile.cpp
qrc_tile.cpp: tile.qrc \
		tile.png
	/usr/bin/rcc -name tile tile.qrc -o qrc_tile.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

Base.o: Base.cpp Base.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Base.o Base.cpp

BaseWall.o: BaseWall.cpp BaseWall.h \
		BitmapObj.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BaseWall.o BaseWall.cpp

BitmapObj.o: BitmapObj.cpp BitmapObj.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BitmapObj.o BitmapObj.cpp

Border.o: Border.cpp Border.h \
		BitmapObj.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Border.o Border.cpp

Clicker.o: Clicker.cpp Clicker.h \
		Sender.h \
		Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Clicker.o Clicker.cpp

Communicator.o: Communicator.cpp Communicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Communicator.o Communicator.cpp

Controller.o: Controller.cpp Controller.h \
		Receiver.h \
		Packet.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		View.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o Controller.cpp

Dispatcher.o: Dispatcher.cpp Dispatcher.h \
		Sender.h \
		Packet.h \
		PacketQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dispatcher.o Dispatcher.cpp

Evaluator.o: Evaluator.cpp Evaluator.h \
		PacketQueue.h \
		Packet.h \
		Receiver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Evaluator.o Evaluator.cpp

Explosion.o: Explosion.cpp Explosion.h \
		RoundObj.h \
		DefaultValues.h \
		BitmapObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Explosion.o Explosion.cpp

GameWindow.o: GameWindow.cpp GameWindow.h \
		View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameWindow.o GameWindow.cpp

InitDialog.o: InitDialog.cpp InitDialog.h \
		GameWindow.h \
		View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		InitVector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InitDialog.o InitDialog.cpp

Initializer.o: Initializer.cpp Initializer.h \
		GameWindow.h \
		View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		InitDialog.h \
		InitVector.h \
		SettingsModel.h \
		Player.h \
		SettingsController.h \
		SettingsDialog.h \
		Communicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Initializer.o Initializer.cpp

main.o: main.cpp Initializer.h \
		GameWindow.h \
		View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h \
		InitDialog.h \
		InitVector.h \
		SettingsModel.h \
		Player.h \
		SettingsController.h \
		SettingsDialog.h \
		Communicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Matrix.o: Matrix.cpp Matrix.h \
		DefaultValues.h \
		BitmapObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Matrix.o Matrix.cpp

Model.o: Model.cpp Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o Model.cpp

NetReceiver.o: NetReceiver.cpp NetReceiver.h \
		Receiver.h \
		Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetReceiver.o NetReceiver.cpp

NetSender.o: NetSender.cpp NetSender.h \
		Sender.h \
		Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NetSender.o NetSender.cpp

OrientedRoundObj.o: OrientedRoundObj.cpp OrientedRoundObj.h \
		RoundObj.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OrientedRoundObj.o OrientedRoundObj.cpp

Packet.o: Packet.cpp Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Packet.o Packet.cpp

PacketQueue.o: PacketQueue.cpp PacketQueue.h \
		Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PacketQueue.o PacketQueue.cpp

Projectile.o: Projectile.cpp Projectile.h \
		DefaultValues.h \
		OrientedRoundObj.h \
		RoundObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Projectile.o Projectile.cpp

QueueReceiver.o: QueueReceiver.cpp QueueReceiver.h \
		Receiver.h \
		Packet.h \
		PacketQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QueueReceiver.o QueueReceiver.cpp

QueueSender.o: QueueSender.cpp QueueSender.h \
		Sender.h \
		Packet.h \
		PacketQueue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QueueSender.o QueueSender.cpp

RoundObj.o: RoundObj.cpp RoundObj.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RoundObj.o RoundObj.cpp

SettingsController.o: SettingsController.cpp SettingsController.h \
		SettingsDialog.h \
		SettingsModel.h \
		Player.h \
		Communicator.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SettingsController.o SettingsController.cpp

SettingsDialog.o: SettingsDialog.cpp SettingsDialog.h \
		SettingsModel.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SettingsDialog.o SettingsDialog.cpp

SettingsModel.o: SettingsModel.cpp SettingsModel.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SettingsModel.o SettingsModel.cpp

Stone.o: Stone.cpp Stone.h \
		BitmapObj.h \
		DefaultValues.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stone.o Stone.cpp

Tank.o: Tank.cpp Tank.h \
		DefaultValues.h \
		OrientedRoundObj.h \
		RoundObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tank.o Tank.cpp

View.o: View.cpp View.h \
		Model.h \
		DefaultValues.h \
		Base.h \
		Border.h \
		BitmapObj.h \
		Matrix.h \
		RoundObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o View.o View.cpp

moc_Communicator.o: moc_Communicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Communicator.o moc_Communicator.cpp

moc_GameWindow.o: moc_GameWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameWindow.o moc_GameWindow.cpp

moc_InitDialog.o: moc_InitDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InitDialog.o moc_InitDialog.cpp

moc_Initializer.o: moc_Initializer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Initializer.o moc_Initializer.cpp

moc_Model.o: moc_Model.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Model.o moc_Model.cpp

moc_SettingsController.o: moc_SettingsController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SettingsController.o moc_SettingsController.cpp

moc_SettingsDialog.o: moc_SettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SettingsDialog.o moc_SettingsDialog.cpp

moc_SettingsModel.o: moc_SettingsModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SettingsModel.o moc_SettingsModel.cpp

moc_View.o: moc_View.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_View.o moc_View.cpp

qrc_tile.o: qrc_tile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_tile.o qrc_tile.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

